site:
  name: applidget-website

  locales: [en, fr]

  seo_title: Applidget - We make Web and Mobile Apps
  meta_description: "Applidget is an Paris-based agency, specialized with Ruby on Rails, HTML5, iOS, Android development."

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
      title: "Home"
      published: true
    - "spirit":
      title: "Spirit"
      published: true
    - "404":
      title: "404 - Page not found"
      published: true