site:
  name: applidget-website

  locales: [en, fr]

  seo_title: Applidget - Web and Mobile application development
  meta_description: "Applidget is a development agency based in Paris, France."

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
        title: "Home page"
        published: true
    - "404":
        title: "Page not found"
        published: true