site:
  name: applidget-website

  locales: [en, fr]

  seo_title: Applidget - We make Web and Mobile Apps
  meta_description: "Applidget is an Paris-based agency, specialized with Ruby on Rails, HTML5, iOS, Android development."

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
      published: true
    - "what_we_do":
      published: true
    - "technologies":
      published: true
    - "event_solutions":
      published: true
    - "team":
      published: true
    - "offers":
      published: true
    - offers/content_type_template:
      templatized: true
      published: true
      model: offers
    - "blogs":
      published: true
    - "404":
      published: true